distributable:
  url: https://github.com/nvbn/thefuck/archive/refs/tags/{{version.raw}}.tar.gz
  strip-components: 1

versions:
  github: nvbn/thefuck/releases/tags

dependencies:
  python.org: '>=3.11'
  # Add other python dependencies here. For example:
  # pip:colorama: '*'
  # pip:decorator: '*'
  # pip:psutil: '*'
  # pip:pyte: '*'
  # pip:wcwidth: '*'

build:
  python-venv.sh {{prefix}}/bin/thefuck

provides:
  - bin/thefuck

test:
  script: |
    thefuck --version
